import type { BoardSpace } from "./types";

export const BOARD_SIZE = 40;

export const BOARD: BoardSpace[] = [
  { id: 0, name: "GO", type: "go" },
  {
    id: 1,
    name: "Mediterranean Ave",
    type: "property",
    price: 60,
    rent: 2,
    color: "brown",
  },
  { id: 2, name: "Community Chest", type: "community-chest" },
  {
    id: 3,
    name: "Baltic Ave",
    type: "property",
    price: 60,
    rent: 4,
    color: "brown",
  },
  { id: 4, name: "Income Tax", type: "tax" },
  {
    id: 5,
    name: "Reading Railroad",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 6,
    name: "Oriental Ave",
    type: "property",
    price: 100,
    rent: 6,
    color: "light-blue",
  },
  { id: 7, name: "Chance", type: "chance" },
  {
    id: 8,
    name: "Vermont Ave",
    type: "property",
    price: 100,
    rent: 6,
    color: "light-blue",
  },
  {
    id: 9,
    name: "Connecticut Ave",
    type: "property",
    price: 120,
    rent: 8,
    color: "light-blue",
  },
  { id: 10, name: "Jail", type: "jail" },
  {
    id: 11,
    name: "St. Charles Place",
    type: "property",
    price: 140,
    rent: 10,
    color: "pink",
  },
  {
    id: 12,
    name: "Electric Company",
    type: "utility",
    price: 150,
    rent: 28,
  },
  {
    id: 13,
    name: "States Ave",
    type: "property",
    price: 140,
    rent: 10,
    color: "pink",
  },
  { id: 14, name: "Community Chest", type: "community-chest" },
  {
    id: 15,
    name: "Virginia Ave",
    type: "property",
    price: 160,
    rent: 12,
    color: "pink",
  },
  {
    id: 16,
    name: "Pennsylvania Railroad",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 17,
    name: "St. James Place",
    type: "property",
    price: 180,
    rent: 14,
    color: "orange",
  },
  { id: 18, name: "Community Chest", type: "community-chest" },
  {
    id: 19,
    name: "Tennessee Ave",
    type: "property",
    price: 180,
    rent: 14,
    color: "orange",
  },
  {
    id: 20,
    name: "Free Parking",
    type: "free-parking",
  },
  {
    id: 21,
    name: "Kentucky Ave",
    type: "property",
    price: 200,
    rent: 16,
    color: "red",
  },
  { id: 22, name: "Chance", type: "chance" },
  {
    id: 23,
    name: "Indiana Ave",
    type: "property",
    price: 200,
    rent: 16,
    color: "red",
  },
  {
    id: 24,
    name: "Illinois Ave",
    type: "property",
    price: 200,
    rent: 16,
    color: "red",
  },
  {
    id: 25,
    name: "B&O Railroad",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 26,
    name: "Atlantic Ave",
    type: "property",
    price: 220,
    rent: 18,
    color: "yellow",
  },
  {
    id: 27,
    name: "Ventnor Ave",
    type: "property",
    price: 220,
    rent: 18,
    color: "yellow",
  },
  { id: 28, name: "Water Works", type: "utility", price: 150, rent: 28 },
  {
    id: 29,
    name: "Marvin Gardens",
    type: "property",
    price: 220,
    rent: 18,
    color: "yellow",
  },
  { id: 30, name: "Go To Jail", type: "go-to-jail" },
  {
    id: 31,
    name: "Pacific Ave",
    type: "property",
    price: 300,
    rent: 22,
    color: "green",
  },
  {
    id: 32,
    name: "North Carolina Ave",
    type: "property",
    price: 300,
    rent: 22,
    color: "green",
  },
  { id: 33, name: "Community Chest", type: "community-chest" },
  {
    id: 34,
    name: "Pennsylvania Ave",
    type: "property",
    price: 320,
    rent: 24,
    color: "green",
  },
  {
    id: 35,
    name: "Short Line",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  { id: 36, name: "Chance", type: "chance" },
  {
    id: 37,
    name: "Park Place",
    type: "property",
    price: 350,
    rent: 26,
    color: "dark-blue",
  },
  { id: 38, name: "Luxury Tax", type: "tax" },
  {
    id: 39,
    name: "Boardwalk",
    type: "property",
    price: 400,
    rent: 28,
    color: "dark-blue",
  },
];

export function getSpace(position: number): BoardSpace {
  const normalized = ((position % BOARD_SIZE) + BOARD_SIZE) % BOARD_SIZE;
  return BOARD[normalized];
}

export function isOwnable(type: BoardSpace["type"]): boolean {
  return type === "property" || type === "railroad" || type === "utility";
}
