import type { DragonCharacter } from "@/lib/dragons/types";

/** Main dragon characters — names are placeholders until you choose them. */
export const DRAGON_CHARACTERS: DragonCharacter[] = [
  {
    id: "skywing",
    tribe: "SkyWing",
    name: "???",
    description: "Fiery red scales with blazing orange and yellow wings.",
    imageUrl: "/dragons/skywing.png",
    colors: {
      primary: "#c41e3a",
      secondary: "#ff6b35",
      accent: "#ffd700",
      wing: "#ff8c00",
      wingInner: "#ffd700",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "mudwing",
    tribe: "MudWing",
    name: "???",
    description: "Thick brown armor and a powerful, crocodile-like build.",
    imageUrl: "/dragons/mudwing.png",
    colors: {
      primary: "#8b5a2b",
      secondary: "#a0522d",
      accent: "#d2691e",
      wing: "#6b4423",
      wingInner: "#cd853f",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: true,
      slim: false,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "seawing",
    tribe: "SeaWing",
    name: "???",
    description: "Deep blue scales with glowing bioluminescent markings.",
    imageUrl: "/dragons/seawing.png",
    colors: {
      primary: "#1e4d7b",
      secondary: "#2e6b9e",
      accent: "#00e5ff",
      wing: "#2563a8",
      wingInner: "#4fc3f7",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: true,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "rainwing",
    tribe: "RainWing",
    name: "???",
    description: "Rainbow scales that shimmer with every color of the jungle.",
    imageUrl: "/dragons/rainwing.png",
    colors: {
      primary: "#2ecc71",
      secondary: "#e74c3c",
      accent: "#9b59b6",
      wing: "#3498db",
      wingInner: "#f39c12",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "sandwing",
    tribe: "SandWing",
    name: "???",
    description: "Pale gold scales, a spine sail, and a venomous tail barb.",
    imageUrl: "/dragons/sandwing.png",
    colors: {
      primary: "#e8c872",
      secondary: "#d4a843",
      accent: "#f5deb3",
      wing: "#c9a84c",
      wingInner: "#f0d78c",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: true,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "nightwing",
    tribe: "NightWing",
    name: "???",
    description: "Midnight black scales with star-speckled wing undersides.",
    imageUrl: "/dragons/nightwing.png",
    colors: {
      primary: "#1a1a2e",
      secondary: "#2d2d44",
      accent: "#c0c0ff",
      wing: "#0f0f1a",
      wingInner: "#e8e8ff",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: true,
      hasStripes: false,
    },
  },
  {
    id: "leafwing",
    tribe: "LeafWing",
    name: "???",
    description: "Leaf-shaped wings and a graceful, jungle-green body.",
    imageUrl: "/dragons/leafwing.png",
    colors: {
      primary: "#4caf50",
      secondary: "#81c784",
      accent: "#a5d6a7",
      wing: "#66bb6a",
      wingInner: "#c8e6c9",
    },
    traits: {
      wingCount: 4,
      wingStyle: "leaf",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "icewing",
    tribe: "IceWing",
    name: "???",
    description: "Shimmering white and ice-blue scales with sharp spikes.",
    imageUrl: "/dragons/icewing.png",
    colors: {
      primary: "#e8f4f8",
      secondary: "#b3d9e8",
      accent: "#87ceeb",
      wing: "#d0e8f0",
      wingInner: "#ffffff",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: false,
      hasSpikes: true,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "hivewing",
    tribe: "HiveWing",
    name: "???",
    description: "Yellow and black stripes with four thin, insect-like wings.",
    imageUrl: "/dragons/hivewing.png",
    colors: {
      primary: "#f4d03f",
      secondary: "#1a1a1a",
      accent: "#f7dc6f",
      wing: "#f9e79f",
      wingInner: "#fef9e7",
    },
    traits: {
      wingCount: 4,
      wingStyle: "insect",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: true,
    },
  },
  {
    id: "silkwing",
    tribe: "SilkWing",
    name: "???",
    description: "Vibrant blue and purple scales with butterfly wings.",
    imageUrl: "/dragons/silkwing.png",
    colors: {
      primary: "#5b4fc7",
      secondary: "#7b68ee",
      accent: "#dda0dd",
      wing: "#6a5acd",
      wingInner: "#e6e6fa",
    },
    traits: {
      wingCount: 4,
      wingStyle: "butterfly",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: true,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
];
