import type { DragonCharacter } from "@/lib/dragons/types";

/** Main dragon characters — names are placeholders until you choose them. */
export const DRAGON_CHARACTERS: DragonCharacter[] = [
  {
    id: "skywing",
    tribe: "SkyWing",
    name: "???",
    colors: {
      primary: "#c41e3a",
      secondary: "#ff6b35",
      accent: "#ffd700",
      wing: "#ff8c00",
      wingInner: "#ffd700",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "mudwing",
    tribe: "MudWing",
    name: "???",
    colors: {
      primary: "#8b5a2b",
      secondary: "#a0522d",
      accent: "#d2691e",
      wing: "#6b4423",
      wingInner: "#cd853f",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: true,
      slim: false,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "seawing",
    tribe: "SeaWing",
    name: "???",
    colors: {
      primary: "#1e4d7b",
      secondary: "#2e6b9e",
      accent: "#0ea5e9",
      wing: "#2563a8",
      wingInner: "#38bdf8",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: true,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "rainwing",
    tribe: "RainWing",
    name: "???",
    colors: {
      primary: "#16a34a",
      secondary: "#dc2626",
      accent: "#7c3aed",
      wing: "#2563eb",
      wingInner: "#ea580c",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "sandwing",
    tribe: "SandWing",
    name: "???",
    colors: {
      primary: "#e8c872",
      secondary: "#d4a843",
      accent: "#f5deb3",
      wing: "#c9a84c",
      wingInner: "#f0d78c",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: true,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "nightwing",
    tribe: "NightWing",
    name: "???",
    colors: {
      primary: "#1a1a2e",
      secondary: "#2d2d44",
      accent: "#c0c0ff",
      wing: "#0f0f1a",
      wingInner: "#e8e8ff",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: true,
      hasStripes: false,
    },
  },
  {
    id: "leafwing",
    tribe: "LeafWing",
    name: "???",
    colors: {
      primary: "#1b5e20",
      secondary: "#2e7d32",
      accent: "#4caf50",
      wing: "#166534",
      wingInner: "#4caf50",
    },
    traits: {
      wingCount: 4,
      wingStyle: "leaf",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "icewing",
    tribe: "IceWing",
    name: "???",
    colors: {
      primary: "#5fb8d9",
      secondary: "#2f7ea3",
      accent: "#bfe9f7",
      wing: "#3d8fb0",
      wingInner: "#eaf7fb",
    },
    traits: {
      wingCount: 2,
      wingStyle: "classic",
      bulky: false,
      slim: false,
      hasTailBarb: false,
      hasSpikes: true,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
  {
    id: "hivewing",
    tribe: "HiveWing",
    name: "???",
    colors: {
      primary: "#f4d03f",
      secondary: "#1a1a1a",
      accent: "#f7dc6f",
      wing: "#f9e79f",
      wingInner: "#fef9e7",
    },
    traits: {
      wingCount: 4,
      wingStyle: "insect",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: false,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: true,
    },
  },
  {
    id: "silkwing",
    tribe: "SilkWing",
    name: "???",
    colors: {
      primary: "#5b4fc7",
      secondary: "#7b68ee",
      accent: "#dda0dd",
      wing: "#6a5acd",
      wingInner: "#e6e6fa",
    },
    traits: {
      wingCount: 4,
      wingStyle: "butterfly",
      bulky: false,
      slim: true,
      hasTailBarb: false,
      hasSpikes: false,
      hasAntennae: true,
      hasBioluminescence: false,
      hasStarryWings: false,
      hasStripes: false,
    },
  },
];
